
# Dependencies

markdown:         kramdown


theme: jekyll-theme-cayman

# Permalinks

permalink:        pretty



# Setup

title:            'The Liz Miller's Site'

url:              http://thelizmiller.github.io

baseurl:          /



github:

  repo:           https://github.com/thelizmiller



author:

  name:           'Liz Miller'

  url:            https://twitter.com/thelizmiller
